version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing 
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the php code
      - echo Running unit tests
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
